<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>int</string>
	</array>
	<key>name</key>
	<string>Interpol</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#interpol</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>(#.*$)</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(self|nil|true|false)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(([1-9][0-9]*|[0-9])(\.[0-9]+)?([eE][+-]?[0-9])?)</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
			</array>
		</dict>
		<key>html</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#mustache-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#mustache-tag</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-doctype</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html-tag</string>
				</dict>
			</array>
		</dict>
		<key>html-comment</key>
		<dict>
			<key>begin</key>
			<string>&lt;!--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--\s*&gt;</string>
			<key>name</key>
			<string>comment.block.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
			</array>
		</dict>
		<key>html-doctype</key>
		<dict>
			<key>begin</key>
			<string>&lt;!</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>meta.tag.sgml.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(DOCTYPE|doctype)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.doctype.html</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=&gt;)</string>
					<key>name</key>
					<string>meta.tag.sgml.doctype.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>"[^"&gt;]*"</string>
							<key>name</key>
							<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s*)(?!--|&gt;)\S(\s*)</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
			</array>
		</dict>
		<key>html-tag</key>
		<dict>
			<key>begin</key>
			<string>(&lt;/?)([$_a-zA-Z][$_a-zA-Z0-9]*)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.name.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.other.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpol</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>match</key>
			<string>\b([$_a-zA-Z][$_a-zA-Z0-9]*)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<key>interpol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\%([1-9][0-9]*|[0-9])(\|[$_a-zA-Z][$_a-zA-Z0-9]*)*;?</string>
					<key>name</key>
					<string>variable.parameter.index</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\%([$_a-zA-Z][$_a-zA-Z0-9]*)(\|[$_a-zA-Z][$_a-zA-Z0-9]*)*;?</string>
					<key>name</key>
					<string>variable.parameter.name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\%(\|[$_a-zA-Z][$_a-zA-Z0-9]*)*;?</string>
					<key>name</key>
					<string>variable.parameter.position</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(and|or|like|lt|gt|lte|le|gte|ge|mod|not|if|unless|else)\b</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([\-+*\/|:@=(),\.\[\]])</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</array>
		</dict>
		<key>ml-string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>\"\"\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\"\"\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.triple</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>ml-string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'''</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'''</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.triple</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>mustache-comment</key>
		<dict>
			<key>begin</key>
			<string>\{+\!</string>
			<key>end</key>
			<string>\}+</string>
			<key>name</key>
			<string>comment.block.mustache</string>
		</dict>
		<key>mustache-tag</key>
		<dict>
			<key>begin</key>
			<string>\{+[&amp;&gt;#^/]?</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.mustache</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}+</string>
			<key>name</key>
			<string>source.mustache.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(for|def|from|import|export|let|if|unless|do|with|as|in|else|end|when|where)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ml-string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ml-string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.interpol</string>
	<key>uuid</key>
	<string>b059aca9-7261-413b-a3f7-1c453843ca89</string>
</dict>
</plist>
